on:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * *'

jobs:
  delete_old_branches:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - name: Build and Deploy Script
        run: bash delete_old_branches.sh false r 30
        shell: bash

