trigger: none
on:
  workflow_dispatch:

schedules:
  - cron: "0 0 0 15 * ? *"
    displayName: cleanup remote git-Branches
    always: true

jobs:
 build:
  steps:
    - name: test
      run: ./delete_old_branches.sh
      shell: bash

